In [1]:
import numpy as np
from numpy import linalg as LA

In [2]:
# def calc_eigen(T:np.array):
def calc_eigen(T):
    #It must be square
    try:
        eigenvalues, eigenvectors=LA.eig(T)
        print(f"eigenvalues:{eigenvalues}")
        print(f"eigenvectors:{eigenvectors}")    
        return eigenvalues, eigenvectors
    except:
        return None,None

In [3]:
def calc_sigma(eValU,eValV,M):
    singular_values=np.sqrt(np.abs(eValV))# No matter if using eValU or eValV
    singular_values=np.sort(singular_values)[::-1]
    
    m,n=M.shape
    sigma=np.zeros((m,n))
    
    np.fill_diagonal(sigma,singular_values[:min(n,m)])
    
    return sigma
     

In [4]:
M=np.array([[1,0.5],[2,0.8]])
M=np.array([[3,2,2],[2,3,-2]])

In [5]:
eigenvalues, eigenvectors=calc_eigen(M)


In [6]:
if eigenvalues is not None and eigenvectors is not None:    
    print("Done")

In [7]:
if not( eigenvalues is not None and eigenvectors is not None):
    # use SVD 
    # M = Ub Sigma  (Vb transpose)
    # U = M (M transpose)
    # V = (M transpose) M
    
    Mt= M.transpose()
    
    U= np.matmul(M,Mt)
    V=np.matmul(Mt,M)
    
    
    # print("\n*** U ***")
    # print(U)
    eValU,eVecU=calc_eigen(U)
    Ub=eVecU
    
    print("\n*** Ub ***")
    print(Ub)
    
    # print("\n*** V ***")
    # print(V)
    eValV,eVecV=calc_eigen(V)
    Vb=eVecV
    
    print("\n*** Vb ***")
    print(Vb)
    
    # VbT=np.transpose(Vb)
    VbT=Vb.transpose()
    print("\n*** Vb^T ***")
    print(VbT)
    
    sigma= calc_sigma(eValU,eValV,M)
    print("\n*** Sigma ***")
    print(f"{sigma}")   
    
    # Verify reconstruction of M
    print("\n*** Test ***")
    new_M=np.matmul(Ub,np.matmul(sigma,VbT))
    print(f"org M:{M}")
    print(f"new M:{new_M}")
    

    

eigenvalues:[25.  9.]
eigenvectors:[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]

*** Ub ***
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
eigenvalues:[2.5000000e+01 5.0324328e-15 9.0000000e+00]
eigenvectors:[[-7.07106781e-01 -6.66666667e-01  2.35702260e-01]
 [-7.07106781e-01  6.66666667e-01 -2.35702260e-01]
 [-4.55680392e-17  3.33333333e-01  9.42809042e-01]]

*** Vb ***
[[-7.07106781e-01 -6.66666667e-01  2.35702260e-01]
 [-7.07106781e-01  6.66666667e-01 -2.35702260e-01]
 [-4.55680392e-17  3.33333333e-01  9.42809042e-01]]

*** Vb^T ***
[[-7.07106781e-01 -7.07106781e-01 -4.55680392e-17]
 [-6.66666667e-01  6.66666667e-01  3.33333333e-01]
 [ 2.35702260e-01 -2.35702260e-01  9.42809042e-01]]

*** Sigma ***
[[5. 0. 0.]
 [0. 3. 0.]]

*** Test ***
org M:[[ 3  2  2]
 [ 2  3 -2]]
new M:[[-1.08578644 -3.91421356 -0.70710678]
 [-3.91421356 -1.08578644  0.70710678]]


In [8]:
if not( eigenvalues is not None and eigenvectors is not None):
    # Transpose of M
    Mt = M.transpose()

    # U = M * M^T
    U = np.matmul(M, Mt)

    # V = M^T * M
    V = np.matmul(Mt, M)

    # Calculate eigenvalues and eigenvectors
    eValU, eVecU = calc_eigen(U)
    eValV, eVecV = calc_eigen(V)

    
    # Sort eigenvectors of U and V according to eigenvalues
    sorted_indices_U = np.argsort(-eValU)  # Descending order
    sorted_indices_V = np.argsort(-eValV)  # Descending order

    Ub = eVecU[:, sorted_indices_U]  # U eigenvectors
    Vb = eVecV[:, sorted_indices_V]  # V eigenvectors
    VbT = Vb.transpose()  # Transpose of V

    # Calculate Sigma
    sigma = calc_sigma(eValU, eValV, M)

    # Verify reconstruction of M
    reconstructed_M = np.matmul(Ub, np.matmul(sigma, VbT))

    # Output results
    print("\n*** Ub ***")
    print(Ub)

    print("\n*** Sigma ***")
    print(sigma)

    print("\n*** Vb^T ***")
    print(VbT)

    print("\n*** Original M ***")
    print(M)

    print("\n*** Reconstructed M ***")
    print(reconstructed_M)    

eigenvalues:[25.  9.]
eigenvectors:[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
eigenvalues:[2.5000000e+01 5.0324328e-15 9.0000000e+00]
eigenvectors:[[-7.07106781e-01 -6.66666667e-01  2.35702260e-01]
 [-7.07106781e-01  6.66666667e-01 -2.35702260e-01]
 [-4.55680392e-17  3.33333333e-01  9.42809042e-01]]

*** Ub ***
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]

*** Sigma ***
[[5. 0. 0.]
 [0. 3. 0.]]

*** Vb^T ***
[[-7.07106781e-01 -7.07106781e-01 -4.55680392e-17]
 [ 2.35702260e-01 -2.35702260e-01  9.42809042e-01]
 [-6.66666667e-01  6.66666667e-01  3.33333333e-01]]

*** Original M ***
[[ 3  2  2]
 [ 2  3 -2]]

*** Reconstructed M ***
[[-3. -2. -2.]
 [-2. -3.  2.]]
