In [62]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn
from sklearn.linear_model import SGDRegressor
import os

notebook_path = os.getcwd()

In [63]:
# Datasets path
# usa-housing_data
csv_train_path = f"{notebook_path}/usa-housing_data/usa-housing-train-preprocessed.csv"
csv_test_path = f"{notebook_path}/usa-housing_data/usa-housing-test-preprocessed.csv"

# simple_one_feature
# csv_train_path = (
#     f"{notebook_path}/test_data/simple_one_feature_housing-train-preprocessed.csv"
# )
# csv_test_path = (
#     f"{notebook_path}/test_data/simple_one_feature_housing-test-preprocessed.csv"
# )

In [64]:
def load_csv_as_augmented(csv_path):
    assert os.path.exists(csv_path), "File not exists, " + csv_path
    df = pd.read_csv(csv_path)
    print(df.columns)
    d = np.array(df)[:, 1:]
    x = d[:, :-1]
    x_aug = np.hstack((np.ones((x.shape[0], 1)), x))
    y = d[:, -1]
    print(f"x_aug.shape: {x_aug.shape}, y.shape: {y.shape}")
    return x_aug, y

In [65]:
def load_csv(csv_path):
    assert os.path.exists(csv_path), "File not exists, " + csv_path
    df = pd.read_csv(csv_path)
    print(df.columns)
    d = np.array(df)[:, 1:]
    x = d[:, :-1]
    y = d[:, -1]
    print(f"x.shape: {x.shape}, y.shape: {y.shape}")
    return x, y

In [66]:
x_train, y_train = load_csv(csv_train_path)
x_test, y_test = load_csv(csv_test_path)

Index(['Unnamed: 0', 'Avg. Area Income', 'Avg. Area House Age',
       'Avg. Area Number of Rooms', 'Avg. Area Number of Bedrooms',
       'Area Population', 'Price'],
      dtype='object')
x.shape: (3500, 5), y.shape: (3500,)
Index(['Unnamed: 0', 'Avg. Area Income', 'Avg. Area House Age',
       'Avg. Area Number of Rooms', 'Avg. Area Number of Bedrooms',
       'Area Population', 'Price'],
      dtype='object')
x.shape: (1500, 5), y.shape: (1500,)


In [67]:
model=SGDRegressor(verbose=1,eta0=0.001,tol=1e-7)
print(model)

SGDRegressor(eta0=0.001, tol=1e-07, verbose=1)


In [68]:
model.fit(x_train,y_train)
model.intercept_,model.coef_

-- Epoch 1
Norm: 0.15, NNZs: 5, Bias: 0.558666, T: 3500, Avg. loss: 0.436201
Total training time: 0.00 seconds.
-- Epoch 2
Norm: 0.21, NNZs: 5, Bias: 0.786039, T: 7000, Avg. loss: 0.169041
Total training time: 0.00 seconds.
-- Epoch 3
Norm: 0.25, NNZs: 5, Bias: 0.921098, T: 10500, Avg. loss: 0.080950
Total training time: 0.00 seconds.
-- Epoch 4
Norm: 0.27, NNZs: 5, Bias: 1.008788, T: 14000, Avg. loss: 0.043162
Total training time: 0.00 seconds.
-- Epoch 5
Norm: 0.29, NNZs: 5, Bias: 1.068356, T: 17500, Avg. loss: 0.025212
Total training time: 0.00 seconds.
-- Epoch 6
Norm: 0.30, NNZs: 5, Bias: 1.110184, T: 21000, Avg. loss: 0.016141
Total training time: 0.00 seconds.
-- Epoch 7
Norm: 0.31, NNZs: 5, Bias: 1.140059, T: 24500, Avg. loss: 0.011354
Total training time: 0.00 seconds.
-- Epoch 8
Norm: 0.32, NNZs: 5, Bias: 1.161891, T: 28000, Avg. loss: 0.008741
Total training time: 0.00 seconds.
-- Epoch 9
Norm: 0.32, NNZs: 5, Bias: 1.178083, T: 31500, Avg. loss: 0.007270
Total training time:

(array([1.23120353]),
 array([0.23043155, 0.16412463, 0.12009492, 0.00334302, 0.1509729 ]))

In [69]:
model.score(x_train,y_train)

0.9192970827540691

In [70]:
model.score(x_test,y_test)

0.9146556026299291

In [71]:
model.predict([x_test[0]])

array([1.30838357])