# <font color='#FFE15D'>**Week 11: Logistic Regression 🔴🔵**</font>

## **🔸 Logistic Regression (sklearn)**

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression, SGDClassifier

from sklearn.datasets import load_breast_cancer, make_classification, make_blobs, make_circles

In [3]:
X, y = load_breast_cancer(return_X_y=True)
X.shape, y.shape

((569, 30), (569,))

In [4]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
x_train.shape, y_train.shape, x_test.shape, y_test.shape

((455, 30), (455,), (114, 30), (114,))

### `LogisticRegression()`

In [5]:
LogisticRegression()

LogisticRegression()

In [6]:
# model = LogisticRegression()
model = LogisticRegression(solver='sag', max_iter=200, random_state=14)
model.fit(x_train, y_train)
model.predict(x_test), y_test

d:\venv\venv_general_312\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


(array([0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0,
        0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0,
        1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0,
        1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1,
        1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1,
        0, 1, 1, 1]),
 array([0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0,
        0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0,
        1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0,
        0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1,
        1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1,
        0, 0, 0, 1]))

In [7]:
model.predict_proba(x_test)
# model.predict_proba(x_test).sum(1)

array([[9.98051901e-01, 1.94809906e-03],
       [5.44292065e-02, 9.45570793e-01],
       [2.26722198e-02, 9.77327780e-01],
       [7.60289366e-02, 9.23971063e-01],
       [9.99974628e-01, 2.53715531e-05],
       [8.83454506e-02, 9.11654549e-01],
       [6.08210427e-02, 9.39178957e-01],
       [7.34300413e-02, 9.26569959e-01],
       [6.23731289e-02, 9.37626871e-01],
       [3.58264402e-01, 6.41735598e-01],
       [9.99963397e-01, 3.66032490e-05],
       [4.21476084e-01, 5.78523916e-01],
       [1.36823540e-01, 8.63176460e-01],
       [6.94694466e-02, 9.30530553e-01],
       [9.24400990e-01, 7.55990096e-02],
       [8.47848573e-01, 1.52151427e-01],
       [1.44672490e-01, 8.55327510e-01],
       [9.99999797e-01, 2.03002894e-07],
       [9.37710583e-02, 9.06228942e-01],
       [8.98790134e-02, 9.10120987e-01],
       [1.53283944e-01, 8.46716056e-01],
       [9.99999313e-01, 6.87349535e-07],
       [9.81008058e-01, 1.89919424e-02],
       [8.15065318e-01, 1.84934682e-01],
       [8.678119

In [8]:
model.predict_log_proba(x_test)

array([[-1.94999907e-03, -6.24090122e+00],
       [-2.91085438e+00, -5.59665196e-02],
       [-3.78661490e+00, -2.29331865e-02],
       [-2.57664127e+00, -7.90745245e-02],
       [-2.53718750e-05, -1.05818820e+01],
       [-2.42650057e+00, -9.24941443e-02],
       [-2.79981945e+00, -6.27492351e-02],
       [-2.61142215e+00, -7.62657275e-02],
       [-2.77462072e+00, -6.44032011e-02],
       [-1.02648401e+00, -4.43578902e-01],
       [-3.66039189e-05, -1.02153736e+01],
       [-8.63992243e-01, -5.47275392e-01],
       [-1.98906321e+00, -1.47136136e-01],
       [-2.66686824e+00, -7.20003680e-02],
       [-7.86093292e-02, -2.58231210e+00],
       [-1.65053229e-01, -1.88287902e+00],
       [-1.93328278e+00, -1.56270831e-01],
       [-2.03002915e-07, -1.54100456e+01],
       [-2.36689902e+00, -9.84633099e-02],
       [-2.40929081e+00, -9.41777360e-02],
       [-1.87546323e+00, -1.66389876e-01],
       [-6.87349771e-07, -1.41904229e+01],
       [-1.91746058e-02, -3.96374048e+00],
       [-2.

In [9]:
model.score(x_train, y_train)

0.9230769230769231

In [10]:
model.score(x_test, y_test)

0.9035087719298246

### My test: Using class_weight

In [19]:
model = LogisticRegression(solver='sag', max_iter=200,class_weight="balanced", random_state=14)
model.fit(x_train, y_train)
model.predict(x_test)
model.score(x_train, y_train)
model.score(x_test, y_test)

d:\venv\venv_general_312\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


0.9298245614035088

In [22]:
model = LogisticRegression(solver='sag', max_iter=200,class_weight={0:0.1,1:0.2,3:1}, random_state=14)
model.fit(x_train, y_train)
model.predict(x_test)
model.score(x_train, y_train)
model.score(x_test, y_test)

d:\venv\venv_general_312\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


0.8245614035087719

In [182]:
import numpy as np

print(x_test.shape[1])
feature_weights = {i: np.random.uniform(0.0, 1.0) for i in range(x_test.shape[1])}
feature_weights.update({0: 0.1, 1: 0.2, 3: 1.0})
# feature_weights[0] = 0.2
# feature_weights[1] = .1
# # feature_weights[3] = 1
print(feature_weights)
model = LogisticRegression(
    solver="sag", max_iter=200, class_weight=feature_weights, random_state=14
)
model.fit(x_train, y_train)
model.predict(x_test)
model.score(x_train, y_train)
model.score(x_test, y_test)

30
{0: 0.1, 1: 0.2, 2: 0.4538732436939583, 3: 1.0, 4: 0.7884186991108686, 5: 0.4510070179728851, 6: 0.4586817470530491, 7: 0.5973994413171365, 8: 0.5688461432586203, 9: 0.7188003408002374, 10: 0.8109724390402808, 11: 0.9794201109479721, 12: 0.4965749882238989, 13: 0.7856699255451274, 14: 0.09715465124213185, 15: 0.6401084967772489, 16: 0.8002823634302463, 17: 0.2343341604904805, 18: 0.4701983346240117, 19: 0.6855187295107676, 20: 0.699802427408709, 21: 0.2947661831532681, 22: 0.6488150536313508, 23: 0.12376572961088139, 24: 0.9852194277865441, 25: 0.9451421991285124, 26: 0.6240024650698419, 27: 0.22181246955094147, 28: 0.3765262073835529, 29: 0.426775352436394}


d:\venv\venv_general_312\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


0.8245614035087719

### `SGDClassifier()`

In [12]:
model = SGDClassifier(loss='log_loss', random_state=27)
model.fit(x_train, y_train)

SGDClassifier(loss='log_loss', random_state=27)

In [13]:
model.score(x_train, y_train)

0.9208791208791208

In [14]:
model.score(x_test, y_test)

0.9210526315789473

In [15]:
model = SGDClassifier(loss='hinge', random_state=27)
model.fit(x_train, y_train)
print(model.score(x_train, y_train))
print(model.score(x_test, y_test))

0.9098901098901099
0.9298245614035088
